# Generated by Django 5.0.7 on 2024-08-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('usr_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_password', models.CharField(blank=True, max_length=255, null=True)),
                ('usr_last_login', models.DateTimeField()),
                ('usr_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('usr_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('usr_email', models.EmailField(max_length=255, null=True)),
                ('usr_whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('usr_lon', models.CharField(blank=True, max_length=255, null=True)),
                ('usr_is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BrandLevel',
            fields=[
                ('brl_level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brl_brand_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCategoryMaster',
            fields=[
                ('ccm_category_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('ccm_category_name', models.CharField(max_length=255, unique=True)),
                ('ccm_status_id', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('cou_country_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cou_country_name', models.CharField(max_length=255, unique=True)),
                ('cou_country_short_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankMaster',
            fields=[
                ('qbm_question_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('qbm_question_text', models.TextField()),
                ('qbm_answer_text', models.TextField()),
                ('qbm_difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=6)),
                ('qbm_demo_trial', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('qbm_Question_voice_file', models.ImageField(upload_to='media')),
                ('qbm_brand_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.brandlevel')),
            ],
        ),
        migrations.CreateModel(
            name='LegalTermsMaster',
            fields=[
                ('ltm_legal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ltm_page_content_text', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankCategory',
            fields=[
                ('qbc_category_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('qbc_category_name', models.CharField(max_length=255, unique=True)),
                ('qbc_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('rom_role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rom_role_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('set_settings_id', models.IntegerField(primary_key=True, serialize=False)),
                ('set_video_authentication_enable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=6)),
                ('set_voice_authentication_enable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=6)),
                ('set_sms_authentication_enable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=6)),
                ('set_email_authentication_enable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=6)),
                ('set_whatsapp_authentication_enable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevelMaster',
            fields=[
                ('slm_level_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('slm_skill_level_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillMaster',
            fields=[
                ('skm_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('skm_skill_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTypeMaster',
            fields=[
                ('stm_skill_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('stm_skill_type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('Sts_Status_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Sts_Status_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityID',
            fields=[
                ('uai_ACTIVITY_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('uai_ACTIVITY_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompanyExperienceTransaction',
            fields=[
                ('uce_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.users')),
                ('uce_experience_id', models.IntegerField(primary_key=True)),
                ('uce_years_of_experience', models.SmallIntegerField(null=True)),
                ('uce_month_of_experience', models.DecimalField(decimal_places=2, max_digits=4)),
                ('uce_created_at', models.DateTimeField(null=True)),
                ('uce_company_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.companycategorymaster')),
            ],
        ),
        migrations.CreateModel(
            name='UsersFace',
            fields=[
                ('usf_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.users')),
                ('usf_face_registration_file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UsersVoice',
            fields=[
                ('usv_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.users')),
                ('usv_user_voice_registration_file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('com_company_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('com_company_name', models.CharField(max_length=255, unique=True)),
                ('com_company_contact_person', models.CharField(max_length=255)),
                ('com_company_contact_person_email', models.CharField(max_length=255)),
                ('com_company_contact_person_mobile', models.CharField(max_length=255)),
                ('com_company_url', models.CharField(max_length=255)),
                ('com_company_logo', models.ImageField(upload_to='media/')),
                ('com_company_primary_address', models.CharField(max_length=255)),
                ('com_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.companycategorymaster')),
                ('com_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('sttm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.countrymaster')),
                ('sttm_state_id', models.IntegerField(primary_key=True)),
                ('sttm_state_name', models.CharField(max_length=255, unique=True)),
                ('sttm_state_short_name', models.CharField(max_length=10)),
                ('sstm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewResultDetails',
            fields=[
                ('ird_users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.users')),
                ('ird_interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='CRUD.usersinterviewschedule', to_field='uis_interview_id')),
                ('ird_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='CRUD.questionbankmaster')),
                ('ird_users_answers_audio_file', models.FileField(upload_to='audio_files/')),
                ('ird_users_answers_video_file', models.FileField(upload_to='video_files/')),
                ('ird_answers_transcript', models.TextField()),
                ('ird_marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ird_datetime', models.DateTimeField()),
                ('ird_synonyms_words_list', models.TextField()),
                ('ird_phrases_matched_list', models.TextField()),
                ('ird_grammar_mistake', models.TextField()),
                ('ird_keywords_out_of_matching', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersLegaltermsAcceptance',
            fields=[
                ('ula_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.users')),
                ('ula_legal_term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='CRUD.legaltermsmaster')),
                ('ula_date_of_acceptance', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='questionbankmaster',
            name='qbm_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.questionbankcategory'),
        ),
        migrations.CreateModel(
            name='UsersInterviewSchedule',
            fields=[
                ('uis_users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.users')),
                ('uis_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='CRUD.rolemaster')),
                ('uis_interview_id', models.IntegerField(primary_key=True)),
                ('uis_date_time', models.DateTimeField(null=True)),
                ('uis_interview_duration_minutes', models.SmallIntegerField(null=True)),
                ('uir_company_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.companycategorymaster')),
            ],
        ),
        migrations.AddField(
            model_name='questionbankmaster',
            name='qbm_level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.skilllevelmaster'),
        ),
        migrations.AddField(
            model_name='questionbankmaster',
            name='qbm_skills_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.skillmaster'),
        ),
        migrations.AddField(
            model_name='skillmaster',
            name='skm_skill_type_id',
            field=models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.CASCADE, to='CRUD.skilltypemaster'),
        ),
        migrations.AddField(
            model_name='users',
            name='usr_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster'),
        ),
        migrations.AddField(
            model_name='skilltypemaster',
            name='stm_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster'),
        ),
        migrations.AddField(
            model_name='skillmaster',
            name='slm_status_id',
            field=models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster'),
        ),
        migrations.AddField(
            model_name='skilllevelmaster',
            name='slm_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster'),
        ),
        migrations.CreateModel(
            name='SgpaCgpaMaster',
            fields=[
                ('sgp_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('sgp_cgpa_value', models.DecimalField(decimal_places=2, max_digits=5, unique=True)),
                ('sgp_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='rom_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster'),
        ),
        migrations.AddField(
            model_name='questionbankmaster',
            name='qbm_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster'),
        ),
        migrations.AddField(
            model_name='questionbankcategory',
            name='qbc_status_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status+', to='CRUD.statusmaster'),
        ),
        migrations.CreateModel(
            name='QualificationLevel',
            fields=[
                ('qua_qualification_level_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('qua_qualification_level_name', models.CharField(max_length=255, unique=True)),
                ('qua_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategoryMaster',
            fields=[
                ('pcm_category_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('pcm_category_Name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('pcm_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.companymaster')),
                ('pcm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMaster',
            fields=[
                ('pln_plan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pln_plan_name', models.CharField(max_length=255)),
                ('pln_plan_description', models.TextField()),
                ('pln_plan_price', models.FloatField()),
                ('pln_plan_validity_days', models.IntegerField()),
                ('pln_max_users', models.IntegerField()),
                ('pln_max_users_roles', models.IntegerField()),
                ('pln_max_interviews', models.IntegerField()),
                ('pln_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.AddField(
            model_name='legaltermsmaster',
            name='ltm_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster'),
        ),
        migrations.CreateModel(
            name='LanguageMaster',
            fields=[
                ('lnm_language_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lnm_language_name', models.CharField(max_length=255, unique=True)),
                ('lnm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTypeMaster',
            fields=[
                ('itm_Type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('itm_title', models.CharField(max_length=255, unique=True)),
                ('itm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='EducationQualificationMaster',
            fields=[
                ('eqm_education_qualification_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('eqm_education_qualification_name', models.CharField(max_length=255, unique=True)),
                ('eqm_qualification_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.qualificationlevel')),
                ('eqm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_id', models.SmallIntegerField()),
                ('dtm_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('dtm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyMaster',
            fields=[
                ('crm_currency_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('crm_currency_symbol', models.ImageField(upload_to='media/')),
                ('crm_currency_short_code', models.CharField(max_length=10)),
                ('crm_currency_name', models.CharField(max_length=100)),
                ('crm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.countrymaster')),
                ('crm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.AddField(
            model_name='countrymaster',
            name='cou_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster'),
        ),
        migrations.CreateModel(
            name='CountryFlag',
            fields=[
                ('couf_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('couf_country_flag', models.ImageField(upload_to='media/')),
                ('couf_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.countrymaster')),
                ('couf_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMaster',
            fields=[
                ('cma_class_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cma_class_name', models.CharField(max_length=255, unique=True)),
                ('cma_status_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.AddField(
            model_name='brandlevel',
            name='brl_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster'),
        ),
        migrations.CreateModel(
            name='ActiveTypeMaster',
            fields=[
                ('atm_action_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('atm_action_name', models.CharField(max_length=100, unique=True)),
                ('atm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicDurationMaster',
            fields=[
                ('adm_academic_duration_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('adm_duration_name', models.CharField(max_length=255)),
                ('adm_description', models.TextField()),
                ('adm_no_of_years', models.IntegerField()),
                ('adm_no_of_months', models.FloatField()),
                ('adm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('sub_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('sub_subject_name', models.CharField(max_length=255, unique=True)),
                ('sub_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicQualifcationUsersSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqus_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.users')),
                ('aqus_subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.subjectmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyMaster',
            fields=[
                ('tem_technology_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('tem_technology_name', models.CharField(max_length=255, unique=True)),
                ('tem_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TemplatesMaster',
            fields=[
                ('tep_template_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('tep_template_name', models.CharField(max_length=255, unique=True)),
                ('tep_type_for_template', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=20)),
                ('tep_content_of_message', models.TextField()),
                ('tep_status_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLogs',
            fields=[
                ('ual_activity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ual_action_details', models.TextField()),
                ('ual_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserAspirationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uap_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.companymaster')),
                ('uap_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.rolemaster')),
                ('uap_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserProjectExperienceTransaction',
            fields=[
                ('upe_project_experience_id', models.IntegerField(primary_key=True, serialize=False)),
                ('upe_project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upe_project_brief', models.TextField(null=True)),
                ('upe_project_team_size', models.SmallIntegerField(null=True)),
                ('project_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.rolemaster')),
                ('upe_project_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.projectcategorymaster')),
                ('upe_uce_experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.usercompanyexperiencetransaction', to_field='uce_experience_id')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTechnologyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptr_technology_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.technologymaster')),
                ('ptr_project_experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.userprojectexperiencetransaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkillTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukt_skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.skillmaster')),
                ('ukt_skill_level_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.skilllevelmaster')),
                ('ukt_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('uss_subscription_id', models.IntegerField(primary_key=True, serialize=False)),
                ('uss_subscription_start', models.DateField()),
                ('uss_subscription_end', models.DateField()),
                ('uss_puchase_date', models.DateTimeField()),
                ('uss_subscription_amount', models.IntegerField()),
                ('uss_Payment_mode', models.CharField(max_length=255)),
                ('uss_Payment_mode_id', models.IntegerField()),
                ('uss_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.planmaster')),
                ('uss_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
                ('uss_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompanyExperienceTransactionChild',
            fields=[
                ('ucet_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.users')),
                ('uce_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='CRUD.companymaster')),
                ('ucet_experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='CRUD.usercompanyexperiencetransaction', to_field='uce_experience_id')),
                ('ucet_experience_transaction_id', models.IntegerField(primary_key=True)),
                ('uce_from_date', models.DateField(null=True)),
                ('uce_to_date', models.DateField(null=True)),
                ('uce_years_of_experience', models.SmallIntegerField(null=True)),
                ('uce_month_of_experience', models.DecimalField(decimal_places=2, max_digits=4)),
                ('uce_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.rolemaster')),
            ],
        ),
        migrations.AddField(
            model_name='usercompanyexperiencetransaction',
            name='uce_company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.companymaster'),
        ),
        migrations.CreateModel(
            name='UsersDeviceRegistration',
            fields=[
                ('udr_users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.users')),
                ('udr_registration_date', models.DateField(null=True)),
                ('udr_unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('udr_os', models.CharField(blank=True, max_length=255, null=True)),
                ('udr_os_version', models.CharField(blank=True, max_length=255, null=True)),
                ('udr_browser', models.CharField(blank=True, max_length=255, null=True)),
                ('udr_browser_version', models.CharField(blank=True, max_length=255, null=True)),
                ('udr_dtm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.devicetypemaster')),
            ],
        ),
        migrations.CreateModel(
            name='PincodeMaster',
            fields=[
                ('pnm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.countrymaster')),
                ('pnm_pincode_number', models.CharField(max_length=250, primary_key=True)),
                ('pnm_pincode_areaname', models.CharField(max_length=250, unique=True)),
                ('pnm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMaster',
            fields=[
                ('brd_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.countrymaster')),
                ('brd_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='CRUD.statemaster', to_field='sttm_state_id')),
                ('brd_board_id', models.SmallIntegerField(primary_key=True)),
                ('brd_board_name', models.CharField(max_length=255, unique=True)),
                ('brd_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('ctm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.countrymaster')),
                ('ctm_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='CRUD.statemaster', to_field='sttm_state_id')),
                ('ctm_city_id', models.IntegerField(primary_key=True)),
                ('ctm_city_name', models.CharField(max_length=255, unique=True)),
                ('ctm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankKeywords',
            fields=[
                ('qbk_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.questionbankmaster')),
                ('qbk_keywords_id', models.SmallIntegerField(primary_key=True)),
                ('qbk_keyword', models.CharField(max_length=255)),
                ('qbk_synonyms', models.TextField()),
                ('qbk_antonyms', models.TextField()),
                ('qbk_weightage', models.SmallIntegerField()),
                ('qbk_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankNextQuestion',
            fields=[
                ('qbn_original_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='originalq+', serialize=False, to='CRUD.questionbankmaster')),
                ('qbn_eligible_for', models.CharField(choices=[('LT40', 'Less than 40'), ('40TO60', 'Between 40 to 60'), ('60TO80', 'Between 60 to 80'), ('ABOVE80', 'Above 80')], max_length=255)),
                ('qbn_Next_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextq+', to='CRUD.questionbankmaster')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewResultUsers',
            fields=[
                ('irs_users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.users')),
                ('irs_interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='CRUD.usersinterviewschedule', to_field='uis_interview_id')),
                ('irs_result_id', models.IntegerField(primary_key=True)),
                ('irs_overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInterviewReschedule',
            fields=[
                ('uis_users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.users')),
                ('uis_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='CRUD.rolemaster')),
                ('uir_interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='CRUD.usersinterviewschedule', to_field='uis_interview_id')),
                ('uir_reschedule_id', models.IntegerField(primary_key=True)),
                ('uir_date_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='usersinterviewschedule',
            name='uis_interview_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.interviewtypemaster'),
        ),
        migrations.AddField(
            model_name='userprojectexperiencetransaction',
            name='upe_experience_transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.usercompanyexperiencetransactionchild', to_field='ucet_experience_transaction_id'),
        ),
        migrations.CreateModel(
            name='UniversityMaster',
            fields=[
                ('unm_university_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('unm_name', models.CharField(max_length=255, unique=True)),
                ('unm_address', models.CharField(blank=True, max_length=255, null=True)),
                ('unm_lat', models.CharField(max_length=50)),
                ('unm_lon', models.CharField(max_length=50)),
                ('unm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
                ('unm_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CRUD.citymaster', to_field='ctm_city_id')),
                ('unm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CRUD.citymaster', to_field='ctm_country_id')),
                ('unm_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CRUD.citymaster', to_field='ctm_state_id')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMaster',
            fields=[
                ('slm_school_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slm_school_name', models.CharField(max_length=255, unique=True)),
                ('slm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='CRUD.countrymaster')),
                ('slm_address', models.CharField(max_length=255)),
                ('slm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
                ('slm_board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.boardmaster', to_field='brd_board_id')),
                ('slm_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.citymaster', to_field='ctm_city_id')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteMaster',
            fields=[
                ('inm_institute_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('inm_institute_name', models.CharField(max_length=255, unique=True)),
                ('inm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
                ('inm_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CRUD.citymaster', to_field='ctm_city_id')),
                ('inm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CRUD.citymaster', to_field='ctm_country_id')),
                ('inm_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CRUD.citymaster', to_field='ctm_state_id')),
            ],
        ),
        migrations.AddField(
            model_name='companymaster',
            name='com_company_pcity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CRUD.citymaster', to_field='ctm_city_id'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='com_company_pcountry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CRUD.citymaster', to_field='ctm_country_id'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='com_company_pstate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CRUD.citymaster', to_field='ctm_state_id'),
        ),
        migrations.CreateModel(
            name='AcademicQualificationUsers',
            fields=[
                ('aqu_users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRUD.users')),
                ('aqu_year_joining', models.DateField()),
                ('aqu_passing_year', models.DateField()),
                ('aqu_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aqu_trial_of_passing', models.SmallIntegerField()),
                ('aqc_scan_image_of_document', models.ImageField(upload_to='media/')),
                ('acq_class_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class+', to='CRUD.classmaster')),
                ('aqc_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country+', to='CRUD.countrymaster')),
                ('aqc_medium_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medium+', to='CRUD.languagemaster')),
                ('aqc_sgp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sgp+', to='CRUD.sgpacgpamaster')),
                ('aqu_education_qualification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification+', to='CRUD.educationqualificationmaster')),
                ('aqu_institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute+', to='CRUD.institutemaster')),
                ('aqu_university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university+', to='CRUD.universitymaster')),
                ('aqc_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state+', to='CRUD.statemaster', to_field='sttm_state_id')),
                ('aqc_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city+', to='CRUD.citymaster', to_field='ctm_city_id')),
            ],
        ),
    ]
