# Generated by Django 5.0.7 on 2024-07-28 12:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('cou_country_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cou_country_name', models.CharField(max_length=255, unique=True)),
                ('cou_country_short_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('set_settings_id', models.IntegerField(primary_key=True, serialize=False)),
                ('set_video_authentication_enable', models.BooleanField()),
                ('set_voice_authentication_enable', models.BooleanField()),
                ('set_sms_authentication_enable', models.BooleanField()),
                ('set_email_authentication_enable', models.BooleanField()),
                ('set_whatsapp_authentication_enable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('Sts_Status_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Sts_Status_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('sub_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('sub_subject_name', models.CharField(max_length=255, unique=True)),
                ('sub_status_id', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityID',
            fields=[
                ('uai_ACTIVITY_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('uai_ACTIVITY_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLogs',
            fields=[
                ('ual_activity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ual_action_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('sttm_state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sttm_state_name', models.CharField(max_length=255, unique=True)),
                ('sttm_state_short_name', models.CharField(max_length=10)),
                ('sttm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.countrymaster')),
                ('sstm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='skill_type_master',
            fields=[
                ('stm_skill_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('stm_skill_type_name', models.CharField(max_length=100, unique=True)),
                ('stm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statemaster')),
            ],
        ),
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('ctm_city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ctm_city_name', models.CharField(max_length=255)),
                ('ctm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.countrymaster')),
                ('ctm_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statemaster')),
                ('ctm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMaster',
            fields=[
                ('brd_board_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('brd_board_name', models.CharField(max_length=255, unique=True)),
                ('brd_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.countrymaster')),
                ('brd_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statemaster')),
                ('brd_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='skill_master',
            fields=[
                ('skm_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('skm_skill_name', models.CharField(max_length=255, unique=True)),
                ('skm_skill_type_id', models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.CASCADE, to='CRUD.skill_type_master')),
                ('slm_status_id', models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='skill_level_master',
            fields=[
                ('slm_level_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('slm_skill_type_name', models.CharField(max_length=100, unique=True)),
                ('slm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='SgpaCgpaMaster',
            fields=[
                ('sgp_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('sgp_cgpa_valu', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('999.99'))])),
                ('sgp_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMaster',
            fields=[
                ('slm_school_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slm_school_name', models.CharField(max_length=255, unique=True)),
                ('slm_address', models.CharField(max_length=255)),
                ('slm_board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.boardmaster')),
                ('slm_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.citymaster')),
                ('slm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='CRUD.countrymaster')),
                ('slm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('rom_role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rom_role_name', models.CharField(max_length=250, unique=True)),
                ('rom_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationLevel',
            fields=[
                ('qua_qualification_level_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('qua_qualification_level_name', models.CharField(max_length=255, unique=True)),
                ('qua_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMaster',
            fields=[
                ('pln_plan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pln_plan_name', models.CharField(max_length=255, unique=True)),
                ('pln_plan_description', models.TextField()),
                ('pln_plan_price', models.FloatField()),
                ('pln_plan_validity_days', models.IntegerField()),
                ('pln_max_users', models.IntegerField()),
                ('pln_max_users_roles', models.IntegerField()),
                ('pln_max_interviews', models.IntegerField()),
                ('pln_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PincodeMaster',
            fields=[
                ('pnm_country_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('pnm_pincode_number', models.CharField(max_length=250, unique=True)),
                ('pnm_pincode_areaname', models.CharField(max_length=250, unique=True)),
                ('pnm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='LegalTermsMaster',
            fields=[
                ('ltm_legal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ltm_page_content_text', models.CharField(max_length=255, unique=True)),
                ('ltm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageMaster',
            fields=[
                ('lnm_language_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lnm_language_name', models.CharField(max_length=255, unique=True)),
                ('lnm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteMaster',
            fields=[
                ('inm_institute_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('inm_institute_name', models.CharField(max_length=255, unique=True)),
                ('inm_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_institutes', to='CRUD.citymaster')),
                ('inm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_institutes', to='CRUD.citymaster')),
                ('inm_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_institutes', to='CRUD.citymaster')),
                ('inm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='EducationQualificationMaster',
            fields=[
                ('eqm_education_qualification_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('eqm_education_qualification_name', models.CharField(max_length=255, unique=True)),
                ('eqm_qualification_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.qualificationlevel')),
                ('eqm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyMaster',
            fields=[
                ('crm_currency_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('crm_currency_symbol', models.ImageField(upload_to='media/')),
                ('crm_currency_short_code', models.CharField(max_length=10)),
                ('crm_currency_name', models.CharField(max_length=100)),
                ('crm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.countrymaster')),
                ('crm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.AddField(
            model_name='countrymaster',
            name='cou_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster'),
        ),
        migrations.CreateModel(
            name='CountryFlag',
            fields=[
                ('couf_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('couf_country_flag', models.ImageField(upload_to='media/')),
                ('couf_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.countrymaster')),
                ('couf_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMaster',
            fields=[
                ('cma_class_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cma_class_name', models.CharField(max_length=255, unique=True)),
                ('cma_status_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='BrandLevel',
            fields=[
                ('brl_level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brl_brand_name', models.CharField(max_length=255, unique=True)),
                ('brl_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveTypeMaster',
            fields=[
                ('atm_action_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('atm_action_name', models.CharField(max_length=100, unique=True)),
                ('atm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicDurationMaster',
            fields=[
                ('adm_academic_duration_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('adm_duration_name', models.CharField(max_length=255)),
                ('adm_description', models.TextField()),
                ('adm_no_of_years', models.IntegerField()),
                ('adm_no_of_months', models.FloatField()),
                ('adm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyMaster',
            fields=[
                ('tem_technology_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('tem_technology_name', models.CharField(max_length=255, unique=True)),
                ('tem_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityMaster',
            fields=[
                ('unm_university_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('unm_name', models.CharField(max_length=255, unique=True)),
                ('unm_address', models.CharField(blank=True, max_length=255, null=True)),
                ('unm_lat', models.CharField(max_length=50)),
                ('unm_lon', models.CharField(max_length=50)),
                ('unm_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_universities', to='CRUD.citymaster')),
                ('unm_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_universities', to='CRUD.citymaster')),
                ('unm_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_universities', to='CRUD.citymaster')),
                ('unm_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('uss_subscription_id', models.IntegerField(primary_key=True, serialize=False)),
                ('uss_subscription_start', models.DateField()),
                ('uss_subscription_end', models.DateField()),
                ('uss_puchase_date', models.DateTimeField()),
                ('uss_subscription_amount', models.IntegerField()),
                ('uss_Payment_mode', models.CharField(max_length=255)),
                ('uss_Payment_mode_id', models.SmallIntegerField()),
                ('uss_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.planmaster')),
                ('uss_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.statusmaster')),
            ],
        ),
    ]
